name: Build, Test & Publish Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SQLite database (copy from local to temporary dir)
      run: |
        mkdir -p ./data
        cp /home/ubuntu/projet_final_thierno/data/ts_meteo.db ./data/ts_meteo.db

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:${{ github.sha }} .

    - name: Run tests in container
      run: |
        docker run --rm -v $(pwd)/data:/app/data ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:latest pytest tests/

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:latest
