name: Build, Test & Publish Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      db:
        image: nouchka/sqlite # image sqlite temporaire
        volumes:
          - ./data:/app/data
        ports:
          - 8000:8000
        options: --entrypoint ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:${{ github.sha }} .

    - name: Run tests in container
      run: |
        docker run --rm -v $(pwd)/data:/app/data ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:latest pytest tests/

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/api-meteo:latest
